"use client";

import React from "react";
import Link from "next/link";
import {
  FaStickyNote,
  FaBell,
  FaRegFolderOpen,
  FaRobot,
  FaClipboardCheck,
  FaMobileAlt,
  FaCloud,
  FaLock,
} from "react-icons/fa";
import ButtonCommon from "@/app/components/commonComponents/ButtonCommon";
import { GrMagic } from "react-icons/gr";
import { FaEnvelope, FaPhone } from "react-icons/fa";

export default function HomePage() {
  return (
    <div className="container mx-auto">
      {/* Hero Section */}
      <header className="relative text-center h-[92vh] flex items-center justify-center">
        <img
          src="/assets/images/hero.jpg"
          alt="Hero"
          className="absolute inset-0 w-full h-full object-cover shadow-lg"
        />
        <div className="relative z-10 flex flex-col items-center justify-center bg-black bg-opacity-60 rounded-lg p-8">
          <h1 className="text-6xl font-extrabold mb-4 text-white">
            Welcome to Notes Master
          </h1>
          <p className="text-xl text-gray-200 mb-6">
            Your ultimate solution for managing notes and reminders efficiently.
          </p>
          <Link href="/pages/create">
            <ButtonCommon icon={<GrMagic />} label="Take Your First Note" />
          </Link>
        </div>
      </header>

      {/* /* Features Section */}
      <section className="mb-16 text-center min-h-[90vh] h-fit flex flex-col items-center justify-center bg-gray-100 rounded-lg p-8">
        <h2 className="text-4xl font-bold mb-8 text-primary-600">Features</h2>
        <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-12">
          <div className="bg-white p-8 rounded-lg shadow-lg hover:shadow-xl transition-shadow duration-300">
            <div className="bg-primary-100 p-6 rounded-full mb-6 mx-auto w-fit">
              <FaStickyNote className="text-5xl text-primary-600" />
            </div>
            <h3 className="text-2xl font-bold mb-4">Create Notes</h3>
            <p className="text-gray-700">
              Easily create and manage your notes with our intuitive editor. Our
              editor is designed to be user-friendly, allowing you to focus on
              your content without any distractions.
            </p>
          </div>
          <div className="bg-white p-8 rounded-lg shadow-lg hover:shadow-xl transition-shadow duration-300">
            <div className="bg-primary-100 p-6 rounded-full mb-6 mx-auto w-fit">
              <FaBell className="text-5xl text-primary-600" />
            </div>
            <h3 className="text-2xl font-bold mb-4">Set Reminders</h3>
            <p className="text-gray-700">
              Never miss an important task with our reminder feature. Set
              reminders for your notes and get notified at the right time to
              ensure you stay on top of your tasks.
            </p>
          </div>
          <div className="bg-white p-8 rounded-lg shadow-lg hover:shadow-xl transition-shadow duration-300">
            <div className="bg-primary-100 p-6 rounded-full mb-6 mx-auto w-fit">
              <FaRegFolderOpen className="text-5xl text-primary-600" />
            </div>
            <h3 className="text-2xl font-bold mb-4">Organize Efficiently</h3>
            <p className="text-gray-700">
              Keep your notes organized and easily accessible. Use folders and
              tags to categorize your notes, making it simple to find what you
              need when you need it.
            </p>
          </div>
        </div>
      </section>

      {/* Upcoming Features Section */}
      <section className=" text-center mt-8 min-h-[90vh] h-fit flex flex-col items-center justify-center  rounded-lg p-8">
        <h2 className="text-4xl font-bold mb-8 text-primary-600">
          Upcoming Features
        </h2>
        <div className="">
          <div className="flex flex-col md:flex-row items-center mb-8">
            <div className="w-[50%] min-h-[400px]  px-8 flex flex-col justify-center items-center  ">
              <div className="bg-primary-100 p-6 rounded-full mb-6 mx-auto w-fit">
                <FaRobot className="text-5xl text-primary-600" />
              </div>
              <h3 className="text-2xl font-bold mb-4">
                AI Generated Note Summary
              </h3>
              <p className="text-gray-700">
                Get concise summaries of your notes generated by AI. This
                feature will help you quickly review the key points of your
                notes without having to read through all the details.
              </p>
            </div>
            <img
              src="/assets/images/d.png"
              alt="AI Summary"
              className=" w-[50%] max-h-[400px] rounded-lg  "
            />
          </div>

          <div className="flex flex-col md:flex-row items-center">
            <img
              src="/assets/images/b.png"
              alt="AI Tests"
              className="w-[50%] max-h-[400px] rounded-lg"
            />
            <div className="w-[50%] min-h-[400px]  px-8 flex flex-col justify-center items-center  ">
            <div className="bg-primary-100 p-6 rounded-full mb-6 mx-auto w-fit">
                <FaClipboardCheck className="text-5xl text-primary-600" />
              </div>
              <h3 className="text-2xl font-bold mb-4">AI Generated Tests</h3>
              <p className="text-gray-700">
                Evaluate yourself with tests generated by AI based on your
                notes. This feature will create customized tests to help you
                assess your understanding of the material.
              </p>
            </div>
          </div>
        </div>
      </section>
      <section className=" text-center h-[90vh] flex flex-col items-center justify-center bg-gray-100 rounded-lg p-8">
        <h2 className="text-4xl font-bold mb-8 text-primary-600">
          How Notes Master Helps You
        </h2>
        <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-12">
          <div className="bg-white p-8 rounded-lg shadow-lg hover:shadow-xl transition-shadow duration-300">
            <div className="bg-primary-100 p-6 rounded-full mb-6 mx-auto w-fit">
              <FaStickyNote className="text-5xl text-primary-600" />
            </div>
            <h3 className="text-2xl font-bold mb-4">Efficient Note Taking</h3>
            <p className="text-gray-700">
              Capture your thoughts and ideas quickly and efficiently. Our
              platform is designed to help you jot down notes effortlessly,
              ensuring you never miss an important idea.
            </p>
          </div>
          <div className="bg-white p-8 rounded-lg shadow-lg hover:shadow-xl transition-shadow duration-300">
            <div className="bg-primary-100 p-6 rounded-full mb-6 mx-auto w-fit">
              <FaBell className="text-5xl text-primary-600" />
            </div>
            <h3 className="text-2xl font-bold mb-4">Stay Organized</h3>
            <p className="text-gray-700">
              Keep your notes and reminders organized in one place. Use our
              organizational tools to ensure that all your important information
              is easily accessible and well-structured.
            </p>
          </div>
          <div className="bg-white p-8 rounded-lg shadow-lg hover:shadow-xl transition-shadow duration-300">
            <div className="bg-primary-100 p-6 rounded-full mb-6 mx-auto w-fit">
              <FaRegFolderOpen className="text-5xl text-primary-600" />
            </div>
            <h3 className="text-2xl font-bold mb-4">Access Anywhere</h3>
            <p className="text-gray-700">
              Access your notes from any device, anytime, anywhere. Our
              cloud-based platform ensures that your notes are always available,
              no matter where you are.
            </p>
          </div>
        </div>
      </section>
    </div>
  );
}
